sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mconnors/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mconnors/docker-react npm run test
