FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# do we need to keep this yes not cecessary but we may not use docker cpmpoase in the future
COPY . .

CMD ["npm","run","start"]